export const FETCH_WEATHER_DATA = "FETCH_WEATHER_DATA";
export const FETCH_WEATHER_SELECTED_CITY = "FETCH_WEATHER_SELECTED_CITY";
export const FETCH_WEATHER_SELECTED_CITY_FORECAST =
  "FETCH_WEATHER_SELECTED_CITY_FORECAST";
